# Generated by Django 5.1.7 on 2025-03-31 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSugarReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('glucose_level', models.FloatField()),
                ('eye_movement_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='InsulinInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('injection_time', models.DateTimeField(auto_now_add=True)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bloodsugarreading')),
            ],
        ),
    ]
